<?php include_once('components/header.php'); ?>
<?php include_once('components/navbar.php'); ?>

<div class="breadcroumb-area bread-bg" style="background-image: url(assets/img/recentproject.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcroumb-title">
                    <h1>Hydrogen Project</h1>
                    <h6><a href="index.html">Home</a> <i class="far fa-dot-circle"></i> Project's</h6>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="blog-page" class="blog-section section-padding">
    <div class="container">
        <div class="row wow fadeInUp" data-wow-delay=".3s">
            <div class="col-lg-12">
                <div class="single-blog-wrap">
                    <img src="assets/img/Project1.png" class="w-100" alt>
                    <div class="blog-meta">
                        <span class="mr-3"><i class="far fa-user-circle"></i>Rara Energy</span>
                        <span class="mr-3"><i class="far fa-calendar-alt"></i> Hydrogen Project</span>
                    </div>
                    <h3 style="color:green">Hydrogen Storage Modelling</h3>
                    <p class="mt-2">
                        Rara Energy has been actively engaged in providing comprehensive subsurface support and detailed
                        modeling studies for the safe and efficient hydrogen storage in the ambitious Kintore project.
                    </p>
                    <h2 style="color:green">Kintore Project<h2>
                            <p class="mt-2">
                                Kintore Hydrogen will secure Aberdeenshire’s position at the heart of the innovative
                                green hydrogen economy while providing energy security to the wider UK.

                                The project is aiming to take the surplus electricity generated by Scottish offshore
                                wind to produce green hydrogen which can be used for the decarbonisation of power
                                generation facilities and carbon intensive industrial clusters across the country.

                                The North East has historically been a world leader in the energy sector, and large,
                                first-of-its-kind pioneering projects like Kintore Hydrogen will help unlock investment
                                in wind and hydrogen across the region’s energy sector, retaining that leadership, as we
                                transition to a renewables-led energy system.
                            </p>
                            <div class="row wow fadeInUp" data-wow-delay=".3s">
                                <div class="col-lg-4 mb-30">
                                    <img class="blog-inside" src="assets/img/project2.jpg" alt>
                                </div>
                                <div class="col-lg-4">
                                    <img class="blog-inside" src="assets/img/project3.jpg" alt>
                                </div>
                            </div>
                            <h2> <span style="color:green">Who is Statera?</span></h2>
                            <p class="mt-2">
                                Statera is a UK-based energy company that develops, owns and operates flexible
                                generation, battery storage, pumped hydro and green hydrogen projects which will all
                                provide critical grid balancing support in a future renewables-led system.<br>

                                These assets will help the UK build more renewable energy, more quickly, by providing
                                the flexible capacity needed to balance the future grid during periods of extended
                                shortfalls and excesses in renewable generation, due to the variability of wind and
                                solar output. In turn, this technology will lower carbon emissions and deliver best
                                value for energy users.
                            </p>
                            <hr>
                </div>
            </div>
        </div>
    </div>

    <div id="contact-us" class="mb-50 contact-us-area">
        <div class="container">
            <div class="contact-us-wrapper">
                <div class="row wow fadeInUp no-gutters" data-wow-delay=".3s">
                    <div class="col-lg-2 col-md-5 col-6">
                        <div class="contact-us-inner">
                            <h5>3GW</h5>
                            <p>Total electrolyser capacity</p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-5 col-6">
                        <div class="contact-us-inner">
                            <h5>500MW</h5>
                            <p>First phase</p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-5 col-6">
                        <div class="contact-us-inner">
                            <h5>200K</h5>
                            <p>Tonnes of hydrogen per year </p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-5 col-6">
                        <div class="contact-us-inner">
                            <h5>30%</h5>
                            <p>of the UK Government’s IOGW low-carbonhydrogen production target
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-5 col-6">
                        <div class="contact-us-inner">
                            <h5>60%</h5>
                            <p>of the Scottish Government’s 5GW low-carbon hydrogen production target
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-5 col-6">
                        <div class="contact-us-inner">
                            <h5>&#60;30MIN </h5>
                            <p>Response time</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <?php include_once('components/footer.php'); ?>